---
name: Raise PR with Changelog

on:
  push:
    branches:
      - "release-*"

jobs:
  build-and-run-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build and Install Release Notes Tool
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            ./generate-changelog.sh
            cat CHANGELOG.md

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Extract Branch Name
        run: |
          branch_name=$(echo ${{ github.ref }} | cut -d '/' -f 2-)
          echo "## Setting output variable BRANCH_NAME"
          echo "BRANCH_NAME=$branch_name"
        shell: bash
        outputs:
          branch_name: ${{ steps.extract_branch_name.outputs.BRANCH_NAME }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: cut ${{ branch_name }}"
          title: "Cut ${{ branch_name }}"
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: cut ${{ github.ref#refs/heads/ }}"
          title: "Cut ${{ github.ref#refs/heads/ }}"
          body: This PR contains an autogenerated changelog for newer commits. You can view the detailed changes [here](https://github.com/${{ github.repository }}/compare/main...${{ github.sha }})
          branch: changelog-branch
          signoff: true
          delete-branch: true
          labels: release-note-none
