---
name: Raise PR with Changelog

on:
  push:
    branches:
      - "release-*"

jobs:
  build-and-run-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build and Install Release Notes Tool
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            ./generate-changelog.sh
            cat CHANGELOG.md

      - name: Read Tag Name from VERSION File
        id: tag_name
        run: |
          echo "tag_name=$(cat VERSION)" >> $GITHUB_ENV

      - name: Get Base SHA from Tag
        id: base_sha
        run: |
          git rev-list -n 1 "v${{ env.tag_name }}"
        continue-on-error: true

      - name: Get the current SHA
        id: current_sha
        run: |
          git rev-parse HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: cut ${{ github.ref_name }}"
          title: "Cut ${{ github.ref_name }}"
          body: |
            This PR contains an autogenerated changelog for newer commits. 
            You can view the list of commits [here](https://github.com/${{ github.repository }}/compare/main...${{ steps.base_sha.outputs.sha }})
          branch: changelog-branch
          signoff: true
          delete-branch: true
          labels: release-note-none
