name: Enforce PR labels after auto-labeling

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
  workflow_run:
      workflows: ['PR-auto-labeler']
      types: [completed]

jobs:
  enforce-label:
    name: EnforceLabel
    runs-on: ubuntu-latest
    steps:
    - name: Enforce Label
      uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "chore,cleanup,fix,bugfix,enhancement,feat,feature,docs,NONE,release-note-none,release-notes-none,kind/CLEANUP,kind/BUGFIX,kind/ENHANCEMENT,kind/FEATURE,kind/CHANGE"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['chore', 'cleanup', 'fix', 'bugfix', 'enhancement', 'feature', 'docs', 'release-note-none', 'kind/CLEANUP', 'kind/BUGFIX', 'kind/ENHANCEMENT', 'kind/FEATURE', 'kind/CHANGE']"
        BANNED_LABELS: "banned,review-requested"

