name: PR-auto-labeler

on: 
  pull_request_target:
    types: [labeled, unlabeled, opened, edited, synchronize]

permissions:
  # Setting up permissions in the workflow to limit the scope of what it can do. Optional!
  contents: read # the config file
  issues: write # for labeling issues (on: issues)
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)
  statuses: write # to generate status
  checks: write # to generate status
    
jobs:

  labeler:
    runs-on: ubuntu-latest

    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  enforcer:
    needs: [ labeler ]
    runs-on: ubuntu-latest
    steps:
    - name: Enforce Required Labels
      uses: yogevbd/enforce-label-action@2.1.0 
      with:
        REQUIRED_LABELS_ANY: "chore,cleanup,fix,bugfix,enhancement,feat,feature,docs,NONE,release-note-none,release-notes-none,kind/CLEANUP,kind/BUGFIX,kind/ENHANCEMENT,kind/FEATURE,kind/CHANGE"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['chore', 'cleanup', 'fix', 'bugfix', 'enhancement', 'feature', 'docs', 'release-note-none', 'kind/CLEANUP', 'kind/BUGFIX', 'kind/ENHANCEMENT', 'kind/FEATURE', 'kind/CHANGE']"

    - name: Add workflow result as comment on PR
      uses: actions/github-script@v6
      if: failure()
      with:
        script: |
          const name = '${{ github.workflow }}';
          const success = '${{ job.status }}' === 'success';
          const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}`;
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })
