name: PR Labeler

on:
  pull_request:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

triage:
    runs-on: ubuntu-latest
    steps:


jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Use GitHub Issue Labeler
      uses: github/issue-labeler@v3.3
      with:
        configuration-path: .github/labeler.yml
        not-before: 2024-04-01T02:54:32Z
        enable-versioned-regex: 0
        include-title: 0
        include-body: 1
        sync-labels: 1
        repo-token: ${{ github.token }}