---
name: PR-auto-labeler

on:
  pull_request_target:
    types: [labeled, unlabeled, opened, edited, synchronize]

permissions:
  # Setting up permissions in the workflow to limit the scope of what it can do. Optional!
  contents: read # the config file
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)
  statuses: write # to generate status
  checks: write # to generate status

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch PR Body
        id: fetch_body
        run: |
          body=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r '.body')
          echo "PR Body: $body"
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "$body" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Check for labels in PR body
        run: |
          if [[ ${{ env.BODY }} =~ /kind\ (fix|bugfix|feat|feature|enhancement|change|none|NONE|release-note-none|release-notes-none) ]]; then
            echo "PR body is valid"
          else
            echo "PR body does not contain the type of change. Please refer to CONTRIBUTING.md for more information."
            exit 1
          fi

# Adjust the configuration in /.github/labeler.yml
