name: Build and Run Release Notes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.0.2

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v3.3.0
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build and Install Release Notes
        run: |
          temp_dir="$(mktemp -d)" && \
            git clone --depth=1 -q https://github.com/kubernetes/release.git "${temp_dir}" && \
            cd "${temp_dir}/"  && \
            go build ./cmd/release-notes/ && \
            mv release-notes /usr/local/bin/ && \
            release-notes --help
